name: Keep Render App Alive

on:
  schedule:
    - cron: "*/5 * * * *"   # Every 5 minutes
  workflow_dispatch:        # Allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render App
        run: |
          curl -s https://travel-tour-l0x2.onrender.com/actuator/health

      - name: Ping Render App
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" https://travel-tour-l0x2.onrender.com/actuator/health)
          echo "HTTP Status: $response"

